In [1]:
from glob import glob

gt_validation = glob("/mnt/haojun/itpsea4data/dataset/ADE20K_2021_17_01/annotations_detectron2/validation/*.tif")

In [4]:
gt_validation[0]

'/mnt/haojun/itpsea4data/dataset/ADE20K_2021_17_01/annotations_detectron2/validation/ADE_val_00000001.tif'

In [6]:
from PIL import Image
import numpy as np
gt1 = np.array(Image.open(gt_validation[1]))
np.unique(gt1)

array([    0,     1,     2,     3,     9,    16,   714, 65535],
      dtype=uint16)

In [9]:
gt1_ori = np.array(Image.open(
    "/mnt/haojun/itpsea4data/dataset/ade20k_full/train/label/ADE_train_00000002.tif"
))
np.unique(gt1_ori)

array([    0,     5,     6,    11,    13,    16,    18,    20,    39,
          44,    64,    76,    82,   114,   127,   130,   191,   199,
         204,   239,   263,   478, 65535], dtype=uint16)

In [10]:
np.unique(gt1_ori).astype(np.int16)

array([  0,   5,   6,  11,  13,  16,  18,  20,  39,  44,  64,  76,  82,
       114, 127, 130, 191, 199, 204, 239, 263, 478,  -1], dtype=int16)